CREATE OR REPLACE TRIGGER JRSG_TRIG_MAYUS_PROVEEDORES
BEFORE INSERT ON JRSG_Proveedor 
FOR EACH ROW
BEGIN
    :NEW.NOMBRE_PROVEEDOR := UPPER(:NEW.NOMBRE_PROVEEDOR);
    :NEW.DIRECCION_PROVEEDOR := UPPER(:NEW.DIRECCION_PROVEEDOR);
    :NEW.EMAIL_PROVEEDOR := UPPER(:NEW.EMAIL_PROVEEDOR);
END;
