CREATE OR REPLACE PROCEDURE JRSG_PROC_CRUD_PROVEEDOR(
    OPCION VARCHAR2,
    ID_PROVEEDOR_P NUMBER DEFAULT NULL,
    NOMBRE_PROVEEDOR_P VARCHAR2 DEFAULT NULL,
    DIRECCION_PROVEEDOR_P VARCHAR2 DEFAULT NULL,
    TELEFONO_PROVEEDOR_P NUMBER DEFAULT NULL,
    EMAIL_PROVEEDOR_P VARCHAR2 DEFAULT NULL
)IS
    V_NOMBRE_PROVEEDOR VARCHAR2(100);
BEGIN 
    LOCK TABLE JRSG_Proveedor IN ROW EXCLUSIVE MODE;
    
    IF(UPPER(OPCION) = 'M') THEN
        SELECT NOMBRE_PROVEEDOR 
        INTO V_NOMBRE_PROVEEDOR
        FROM JRSG_Proveedor
        WHERE ID_PROVEEDOR = ID_PROVEEDOR_P;

    ELSIF(UPPER(OPCION) = 'C') THEN
        INSERT INTO JRSG_Proveedor (ID_PROVEEDOR, NOMBRE_PROVEEDOR, DIRECCION_PROVEEDOR, TELEFONO_PROVEEDOR, EMAIL_PROVEEDOR)
        VALUES (JRSG_ID_PROVEEDOR.NEXTVAL, NOMBRE_PROVEEDOR_P, DIRECCION_PROVEEDOR_P, TELEFONO_PROVEEDOR_P, EMAIL_PROVEEDOR_P);

    ELSIF(UPPER(OPCION) = 'U') THEN
        UPDATE JRSG_Proveedor
        SET NOMBRE_PROVEEDOR = NOMBRE_PROVEEDOR_P,
            DIRECCION_PROVEEDOR = DIRECCION_PROVEEDOR_P,
            TELEFONO_PROVEEDOR = TELEFONO_PROVEEDOR_P,
            EMAIL_PROVEEDOR = EMAIL_PROVEEDOR_P
        WHERE ID_PROVEEDOR = ID_PROVEEDOR_P;

    ELSIF(UPPER(OPCION) = 'D') THEN
        DELETE FROM JRSG_Proveedor
        WHERE ID_PROVEEDOR = ID_PROVEEDOR_P;
        
    ELSE
        DBMS_OUTPUT.PUT_LINE('algo');
    END IF;
    
    
    COMMIT;

EXCEPTION
    WHEN STORAGE_ERROR THEN
        RAISE_APPLICATION_ERROR(-6500, 'HAY UN PROBLEMA EN LA MEMORIA');
    WHEN PROGRAM_ERROR THEN
        RAISE_APPLICATION_ERROR(-6501, 'ERROR DE PROGRAMA');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20010, 'UPS, FALLÉ :)');

    ROLLBACK; 
END;
