begin
	jrsg_pro_crear_producto(1, NULL, 'Hilo de coser', 'Hilo de coser multifilamento, 2000 yardas', 1000, NULL, 200);
	jrsg_pro_crear_producto(1, NULL, 'Hilo de bordar', 'Hilo de bordar de colores surtidos, 5 metros', 2000, NULL, 250);
	jrsg_pro_crear_producto(1, NULL, 'Hilo de nylon', 'Hilo resistente y flexible, perfecto para ropa deportiva', 1300, NULL, 300);
	jrsg_pro_crear_producto(1, NULL, 'Hilo de lino', 'Hilo natural, fuerte y transpirable.', 1800, NULL, 200);
	jrsg_pro_crear_producto(2, NULL, 'Cordón de algodón', 'Cordón de algodón trenzado, ideal para manualidades', 1500, NULL, 100);
	jrsg_pro_crear_producto(2, NULL, 'Cordón de nylon', 'Cordón de nylon resistente, perfecto para tejidos', 2000, NULL, 50);
	jrsg_pro_crear_producto(2, NULL, 'Cordón de cuero', 'Cordón duradero y elegante, perfecto para bolsos', 3000, NULL, 70);
	jrsg_pro_crear_producto(2, NULL, 'Cordón encerado', 'Cordón resistente y duradero, ideal para mochilas', 1500, NULL, 40);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de raso', 'Cinta de raso 2 cm de ancho, ideal para decoración', 1200, NULL, 80);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de organza', 'Cinta de organza transparente, 3 cm de ancho', 1800, NULL, 60);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de terciopelo', 'Cinta suave y cálida, ideal para abrigos', 1500, NULL, 50);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de encaje', 'Cinta delicada y elegante, ideal para vestidos', 1800, NULL, 60);
	jrsg_pro_crear_producto(4, NULL, 'Botones de madera', 'Set de botones decorativos de madera, 50 piezas', 2500, NULL,40);
	jrsg_pro_crear_producto(4, NULL, 'Botón de nácar', 'Botón brillante y elegante, ideal para ropa fina', 100, NULL, 90);
	jrsg_pro_crear_producto(4, NULL, 'Botón de plástico', 'Botón resistente y económico, ideal para ropa infantil', 100, NULL, 120);
	jrsg_pro_crear_producto(4, NULL, 'Botón forrado', 'Botón cómodo y resistente, ideal para ropa interior', 150, NULL, 50);
	jrsg_pro_crear_producto(5, NULL, 'Cremallera de metal', 'Cremallera de metal, robusta y duradera', 1200, NULL, 50);
	jrsg_pro_crear_producto(5, NULL, 'Cremallera invisible', 'Cremallera invisible para ropa elegante', 1500, NULL, 60);
	jrsg_pro_crear_producto(5, NULL, 'Cierre de presión', 'Cierre de presión, práctico y fácil de usar', 800, NULL, 70);
	jrsg_pro_crear_producto(5, NULL, 'Cremallera de plástico', 'Cremallera de plástico, ligera y resistente', 900, NULL, 80);
	jrsg_pro_crear_producto(6, NULL, 'Encaje decorativo', 'Encaje decorativo de algodón, 5 metros', 4000, NULL, 30);
	jrsg_pro_crear_producto(6, NULL, 'Encaje de chantilly', 'Encaje de chantilly, elegante y delicado', 2500, NULL, 50);
	jrsg_pro_crear_producto(6, NULL, 'Encaje de guipur', 'Encaje de guipur, textura robusta', 2700, NULL, 60);
	jrsg_pro_crear_producto(6, NULL, 'Encaje elástico', 'Encaje elástico, flexible y cómodo', 2000, NULL, 70);
	jrsg_pro_crear_producto(7, NULL, 'Cinta de pasamanería', 'Cinta de pasamanería decorativa y colorida', 1200, NULL, 50);
	jrsg_pro_crear_producto(7, NULL, 'Trenza de pasamanería', 'Trenza de pasamanería, elegante y texturizada', 1500, NULL, 60);
	jrsg_pro_crear_producto(7, NULL, 'Flecos de pasamanería', 'Flecos de pasamanería que añaden movimiento', 1300, NULL, 70);
	jrsg_pro_crear_producto(7, NULL, 'Galones decorativos', 'Galones decorativos, llamativos y únicos', 1800, NULL, 80);
	jrsg_pro_crear_producto(8, NULL, 'Pegamento textil', 'Pegamento textil, fuerte y seguro para telas', 1100, NULL, 50);
	jrsg_pro_crear_producto(8, NULL, 'Cinta adhesiva doble cara', 'Cinta adhesiva doble cara, ideal para telas', 900, NULL, 60);
	jrsg_pro_crear_producto(8, NULL, 'Pegamento en barra', 'Pegamento en barra, ideal para manualidades', 700, NULL, 70);
	jrsg_pro_crear_producto(8, NULL, 'Pegamento de contacto', 'Pegamento de contacto, adhesión inmediata', 1300, NULL, 80);
	jrsg_pro_crear_producto(9, NULL, 'Agujas de coser a mano', 'Agujas de coser a mano, multiusos', 500, NULL, 50);
	jrsg_pro_crear_producto(9, NULL, 'Agujas de máquina de coser', 'Agujas de máquina de coser, duraderas', 700, NULL, 60);
	jrsg_pro_crear_producto(9, NULL, 'Agujas de Bordado', 'Agujas de bordado con ojo grande, set de 12', 1500, NULL, 100);
	jrsg_pro_crear_producto(9, NULL, 'Agujas para tapicería', 'Agujas para tapicería, resistentes y fuertes', 800, NULL, 80);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de cabeza redonda', 'Alfileres de cabeza redonda, coloridos y útiles', 300, NULL, 50);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de modista', 'Alfileres de modista para alta precisión', 400, NULL, 60);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de seguridad', 'Alfileres de seguridad, seguros y prácticos', 500, NULL, 70);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de acero inoxidable', 'Alfileres de acero inoxidable, duraderos', 600, NULL, 80);
	jrsg_pro_crear_producto(11, NULL, 'Lana merino', 'Lana merino, suave y cálida para tejer', 5000, NULL, 50);
	jrsg_pro_crear_producto(11, NULL, 'Lana acrílica', 'Lana acrílica, resistente y duradera', 3000, NULL, 60);
	jrsg_pro_crear_producto(11, NULL, 'Lana de alpaca', 'Lana de alpaca, ligera y suave al tacto', 7000, NULL, 70);
	jrsg_pro_crear_producto(11, NULL, 'Lana de cachemira', 'Lana de cachemira, lujosa y suave', 9000, NULL, 80);
	jrsg_pro_crear_producto(12, NULL, 'Hilo de lana', 'Hilo de lana, cálido y versátil para tejer', 2500, NULL, 50);
	jrsg_pro_crear_producto(12, NULL, 'Hilo de algodón', 'Hilo de algodón, suave y fresco al tacto', 2000, NULL, 60);
	jrsg_pro_crear_producto(12, NULL, 'Hilo de bambú', 'Hilo de bambú, eco-friendly y duradero', 3000, NULL, 70);
	jrsg_pro_crear_producto(12, NULL, 'Hilo acrílico', 'Hilo acrílico, duradero y fácil de tejer', 1500, NULL, 80);
	jrsg_pro_crear_producto(13, NULL, 'Cinta métrica', 'Cinta métrica, flexible y fácil de usar', 1000, NULL, 50);
	jrsg_pro_crear_producto(13, NULL, 'Regla de costura', 'Regla de costura, precisa para medir', 800, NULL, 60);
	jrsg_pro_crear_producto(13, NULL, 'Calibrador de puntadas', 'Calibrador de puntadas, máxima exactitud', 1200, NULL, 70);
	jrsg_pro_crear_producto(13, NULL, 'Escuadra de sastre', 'Escuadra de sastre, para mayor precisión', 1500, NULL, 80);
	jrsg_pro_crear_producto(14, NULL, 'Lentejuelas', 'Lentejuelas brillantes para decoración', 700, NULL, 50);
	jrsg_pro_crear_producto(14, NULL, 'Apliques de pedrería', 'Apliques de pedrería, elegantes y brillantes', 1200, NULL, 60);
	jrsg_pro_crear_producto(14, NULL, 'Perlas para coser', 'Perlas para coser, clásicas y elegantes', 1500, NULL, 70);
	jrsg_pro_crear_producto(14, NULL, 'Parches bordados', 'Parches bordados, diseños variados y coloridos', 1800, NULL, 80);
end;
