begin
	jrsg_pro_crear_producto(1, NULL, 'Hilo de coser', 'Hilo de coser multifilamento, 2000 yardas', 1000, NULL, 200);
	jrsg_pro_crear_producto(1, NULL, 'Hilo de bordar', 'Hilo de bordar de colores surtidos, 5 metros', 2000, NULL, 250);
	jrsg_pro_crear_producto(1, NULL, 'Hilo de nylon', 'Hilo resistente y flexible, perfecto para ropa deportiva', 1300, NULL, 300);
	jrsg_pro_crear_producto(1, NULL, 'Hilo de lino', 'Hilo natural, fuerte y transpirable.', 1800, NULL, 200);
	jrsg_pro_crear_producto(2, NULL, 'Cordon de algodon', 'Cordon de algodon trenzado, ideal para manualidades', 1500, NULL, 100);
	jrsg_pro_crear_producto(2, NULL, 'Cordon de nylon', 'Cordon de nylon resistente, perfecto para tejidos', 2000, NULL, 50);
	jrsg_pro_crear_producto(2, NULL, 'Cordon de cuero', 'Cordon duradero y elegante, perfecto para bolsos', 3000, NULL, 70);
	jrsg_pro_crear_producto(2, NULL, 'Cordon encerado', 'Cordon resistente y duradero, ideal para mochilas', 1500, NULL, 40);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de raso', 'Cinta de raso 2 cm de ancho, ideal para decoracion', 1200, NULL, 80);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de organza', 'Cinta de organza transparente, 3 cm de ancho', 1800, NULL, 60);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de terciopelo', 'Cinta suave y calida, ideal para abrigos', 1500, NULL, 50);
	jrsg_pro_crear_producto(3, NULL, 'Cinta de encaje', 'Cinta delicada y elegante, ideal para vestidos', 1800, NULL, 60);
	jrsg_pro_crear_producto(4, NULL, 'Botones de madera', 'Set de botones decorativos de madera, 50 piezas', 2500, NULL,40);
	jrsg_pro_crear_producto(4, NULL, 'Boton de nacar', 'Boton brillante y elegante, ideal para ropa fina', 100, NULL, 90);
	jrsg_pro_crear_producto(4, NULL, 'Boton de plastico', 'Boton resistente y economico, ideal para ropa infantil', 100, NULL, 120);
	jrsg_pro_crear_producto(4, NULL, 'Boton forrado', 'Boton comodo y resistente, ideal para ropa interior', 150, NULL, 50);
	jrsg_pro_crear_producto(5, NULL, 'Cremallera de metal', 'Cremallera de metal, robusta y duradera', 1200, NULL, 50);
	jrsg_pro_crear_producto(5, NULL, 'Cremallera invisible', 'Cremallera invisible para ropa elegante', 1500, NULL, 60);
	jrsg_pro_crear_producto(5, NULL, 'Cierre de presion', 'Cierre de presion, practico y facil de usar', 800, NULL, 70);
	jrsg_pro_crear_producto(5, NULL, 'Cremallera de plastico', 'Cremallera de plastico, ligera y resistente', 900, NULL, 80);
	jrsg_pro_crear_producto(6, NULL, 'Encaje decorativo', 'Encaje decorativo de algodon, 5 metros', 4000, NULL, 30);
	jrsg_pro_crear_producto(6, NULL, 'Encaje de chantilly', 'Encaje de chantilly, elegante y delicado', 2500, NULL, 50);
	jrsg_pro_crear_producto(6, NULL, 'Encaje de guipur', 'Encaje de guipur, textura robusta', 2700, NULL, 60);
	jrsg_pro_crear_producto(6, NULL, 'Encaje elastico', 'Encaje elastico, flexible y comodo', 2000, NULL, 70);
	jrsg_pro_crear_producto(7, NULL, 'Cinta de pasamaneria', 'Cinta de pasamaneria decorativa y colorida', 1200, NULL, 50);
	jrsg_pro_crear_producto(7, NULL, 'Trenza de pasamaneria', 'Trenza de pasamaneria, elegante y texturizada', 1500, NULL, 60);
	jrsg_pro_crear_producto(7, NULL, 'Flecos de pasamaneria', 'Flecos de pasamaneria que añaden movimiento', 1300, NULL, 70);
	jrsg_pro_crear_producto(7, NULL, 'Galones decorativos', 'Galones decorativos, llamativos y unicos', 1800, NULL, 80);
	jrsg_pro_crear_producto(8, NULL, 'Pegamento textil', 'Pegamento textil, fuerte y seguro para telas', 1100, NULL, 50);
	jrsg_pro_crear_producto(8, NULL, 'Cinta adhesiva doble cara', 'Cinta adhesiva doble cara, ideal para telas', 900, NULL, 60);
	jrsg_pro_crear_producto(8, NULL, 'Pegamento en barra', 'Pegamento en barra, ideal para manualidades', 700, NULL, 70);
	jrsg_pro_crear_producto(8, NULL, 'Pegamento de contacto', 'Pegamento de contacto, adhesion inmediata', 1300, NULL, 80);
	jrsg_pro_crear_producto(9, NULL, 'Agujas de coser a mano', 'Agujas de coser a mano, multiusos', 500, NULL, 50);
	jrsg_pro_crear_producto(9, NULL, 'Agujas de maquina de coser', 'Agujas de maquina de coser, duraderas', 700, NULL, 60);
	jrsg_pro_crear_producto(9, NULL, 'Agujas de Bordado', 'Agujas de bordado con ojo grande, set de 12', 1500, NULL, 100);
	jrsg_pro_crear_producto(9, NULL, 'Agujas para tapiceria', 'Agujas para tapiceria, resistentes y fuertes', 800, NULL, 80);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de cabeza redonda', 'Alfileres de cabeza redonda, coloridos y utiles', 300, NULL, 50);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de modista', 'Alfileres de modista para alta precision', 400, NULL, 60);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de seguridad', 'Alfileres de seguridad, seguros y practicos', 500, NULL, 70);
	jrsg_pro_crear_producto(10, NULL, 'Alfileres de acero inoxidable', 'Alfileres de acero inoxidable, duraderos', 600, NULL, 80);
	jrsg_pro_crear_producto(11, NULL, 'Lana merino', 'Lana merino, suave y calida para tejer', 5000, NULL, 50);
	jrsg_pro_crear_producto(11, NULL, 'Lana acrilica', 'Lana acrilica, resistente y duradera', 3000, NULL, 60);
	jrsg_pro_crear_producto(11, NULL, 'Lana de alpaca', 'Lana de alpaca, ligera y suave al tacto', 7000, NULL, 70);
	jrsg_pro_crear_producto(11, NULL, 'Lana de cachemira', 'Lana de cachemira, lujosa y suave', 9000, NULL, 80);
	jrsg_pro_crear_producto(12, NULL, 'Hilo de lana', 'Hilo de lana, calido y versatil para tejer', 2500, NULL, 50);
	jrsg_pro_crear_producto(12, NULL, 'Hilo de algodon', 'Hilo de algodon, suave y fresco al tacto', 2000, NULL, 60);
	jrsg_pro_crear_producto(12, NULL, 'Hilo de bambu', 'Hilo de bambu, eco-friendly y duradero', 3000, NULL, 70);
	jrsg_pro_crear_producto(12, NULL, 'Hilo acrilico', 'Hilo acrilico, duradero y facil de tejer', 1500, NULL, 80);
	jrsg_pro_crear_producto(13, NULL, 'Cinta metrica', 'Cinta metrica, flexible y facil de usar', 1000, NULL, 50);
	jrsg_pro_crear_producto(13, NULL, 'Regla de costura', 'Regla de costura, precisa para medir', 800, NULL, 60);
	jrsg_pro_crear_producto(13, NULL, 'Calibrador de puntadas', 'Calibrador de puntadas, maxima exactitud', 1200, NULL, 70);
	jrsg_pro_crear_producto(13, NULL, 'Escuadra de sastre', 'Escuadra de sastre, para mayor precision', 1500, NULL, 80);
	jrsg_pro_crear_producto(14, NULL, 'Lentejuelas', 'Lentejuelas brillantes para decoracion', 700, NULL, 50);
	jrsg_pro_crear_producto(14, NULL, 'Apliques de pedreria', 'Apliques de pedreria, elegantes y brillantes', 1200, NULL, 60);
	jrsg_pro_crear_producto(14, NULL, 'Perlas para coser', 'Perlas para coser, clasicas y elegantes', 1500, NULL, 70);
	jrsg_pro_crear_producto(14, NULL, 'Parches bordados', 'Parches bordados, diseños variados y coloridos', 1800, NULL, 80);
end;
