begin
    JRSG_Pro_Crear_Cliente('N/A', 'N/A', 'N/A', '555555555', 'N/A');
    JRSG_Pro_Crear_Cliente('MARIA', 'LOPEZ', 'HERNANDEZ', '5559876543', 'MARIA.LOPEZ@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('CARLOS', 'RAMIREZ', 'MARTINEZ', '5555678901', 'CARLOS.RAMIREZ@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('ANA', 'MARTINEZ', 'GONZALEZ', '5552345678', 'ANA.MARTINEZ@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('PEDRO', 'HERNANDEZ', 'RODRIGUEZ', '5558765432', 'PEDRO.HERNANDEZ@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('LAURA', 'GARCIA', 'TORRES', '5553456789', 'LAURA.GARCIA@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('JORGE', 'RODRIGUEZ', 'ALVAREZ', '5557654321', 'JORGE.RODRIGUEZ@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('SOFIA', 'GONZALEZ', 'FERNANDEZ', '5554567890', 'SOFIA.GONZALEZ@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('LUIS', 'ALVAREZ', 'DOMINGUEZ', '5556543210', 'LUIS.ALVAREZ@EMAIL.COM');
    JRSG_Pro_Crear_Cliente('ELENA', 'FERNANDEZ', 'LOPEZ', '5555432109', 'ELENA.FERNANDEZ@EMAIL.COM');
end;
